### ISSUE TITLE
Bucket names cannot contain '.'

### ISSUE THREAD

**Issue by stonary** [mathcamp/pypicloud#43]
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
shows that the bucket name could/should actually contain "."

    S3 bucket name? test.backet.com
    Bucket names cannot contain '.'

**Comment by stonary** [comment]
just wondering if it is possible to remove the restriction for "." in the next release because all our buckets have "." in it.

**Comment by stevearc** [comment]
While it is legal for a S3 bucket to have a `.` in it, it causes problems. As mentioned [in the docs](http://pypicloud.readthedocs.org/en/latest/topics/storage.html#s3), amazon's SSL certificate is only valid for `*.s3.amazonaws.com` urls. If you have a bucket with a `.` in it, it will appear to not match the certificate and pip will refuse to download the package.

It's possible that this has changed since I wrote it, but I haven't heard anything.

**Comment by stonary** [comment]
that's very helpful, thank you.
