### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by ivanvenosdel** [mathcamp/pypicloud#58]
The Docker image you provide has been quite useful. However it seems to be a bit behind compared the releases. 

Would you mind updating it? 

Or do you recommend people just use it as a base in building their own Dockerfile. If so, I think the docs should be updated to suggest that route.

**Comment by stevearc** [comment]
Sure! I started it as kind of a toy when I began learning about Docker, and have let it slide since. The inexperience really shows (running nginx and uwsgi inside the same container? Gross!). I'll trigger some new builds now and also look into refactoring the format to be more in-line with what you would expect from a docker container.

**Comment by ivanvenosdel** [comment]
If you were to constrain the docker configuration to an S3 store/CDN setup would there be much static file handling left for PyPI? If that is the case you could consider dropping nginx all together and exposing uWSGI directly.

**Comment by stevearc** [comment]
Okay, I've refreshed the setup and moved all the docker files to be in a separate repo over at https://github.com/stevearc/pypicloud-docker so that the images can be updated in a way that isn't tied to the pypicloud release cycle. Let me know if there's anything else you'd like to see from a pypicloud docker image!

**Comment by ivanvenosdel** [comment]
Great, I hope to try this out this week. Thanks!

**Comment by ivanvenosdel** [comment]
Worked well for me.
